### ISSUE TITLE
CLI user_prior.py

### ISSUE THREAD

**Issue by tramsauer** [multiply-org/prior_engine#21]
Status of CLI for user defined priors:

basic command (entry point in `setup.py`) is `multiply_prior_engine.user_prior.main` (could be run from `prior_engine_runner.py` in parent folder if `ModuleNotFoundError`).

There are 4 sub commands (like in in e.g. *git* --> `git branch`, `git merge`, ..):
  - show
  - add
  - remove
  - import

The commands are documented already. 
Please check the CLI out, find help like in every cli with the `-h`-flag. 
What do you think?

**Comment by TonioF** [comment]
When I tried to run user_prior.py, I got an error because prior_logger could not be found. Can you either push that or remove it completely if it isn't relevant?

**Comment by RaT0M** [comment]
should be uploaded. CLI workes for me locally.

**Comment by RaT0M** [comment]
Is the functionality of the CLI good enough for now (knowing that the import function itself still needs more functionality and testing..) ? Then I'll close the issue.

**Comment by TonioF** [comment]
Yes, I think it is good enough for now.
